name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install tox

      - name: Run tests
        run: tox

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v3
